name: list_diff
description: "📃 Calculates a minimal list of operations that convert one list into another if applied in order."
version: 1.1.3
author: Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/list_diff

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  async: ">=2.2.0 <2.5.0"
