name: list_diff
description: "📃 Calculates a minimal list of operations that convert one list into another if applied in order."
version: 1.3.1
homepage: https://github.com/marcelgarus/list_diff

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  async: ^2.2.0
  meta: ^1.1.8

dev_dependencies:
  test: ^1.9.4
