name: list_diff
description: "📃 Calculates a minimal list of operations that convert one list into another if applied in order."
version: 2.0.0
homepage: https://github.com/marcelgarus/list_diff

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.5.0

dev_dependencies:
  test: ^1.16.5
