name: list_diff
description: "📃 Calculates a minimal list of operations that convert one list into another if applied in order."
version: 1.0.1
author: Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/list_diff

environment:
  sdk: ">=2.2.2 <3.0.0"
